In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from PIL import Image

In [23]:
pip install streamlit -q

In [47]:
!wget -q -O - ipv4.icanhazip.com

34.106.164.214

In [ ]:
! streamlit run app.py & npx localtunnel --port 8501

⠙
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

⠹⠸⠼⠴⠦⠧
  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.106.164.214:8501

⠇⠏⠋your url is: https://new-moons-wait.loca.lt

In [25]:

heart_df=pd.read_csv('/content/heart_disease_data.csv')
heart_df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [ ]:
import streamlit as st
from PIL import Image
import numpy as np
st.title('Heart Disease Prediction Model')
input_text= st.text_input('Provide, values separated by comma')
sep_value=input_text.split(',')
img = Image.open('/content/heart image.jpeg')
st.image(img,width=300)

try:
  np_df=np.asarray(sep_value,dtype=float)
  reshaped_df=np_df.reshape(1,-1)
  prediction= model.predict(reshaped_df)
  if prediction[0] == 0:
    st.write('This person doesnt have heart disease')
  else:
    st.write('This person has heart disease')

except ValueError:
  st.write('Please provide csv')

In [26]:
#given data consists of age gender(where 0 is female 1 is male) cp is chest pain type (0 is typical angina and 1 is atypical angina,2 is non anginal pain, 3 is asymptomatic)
#trestbs is resting bp chol is srum cholestrol level  fbs is fasting blood sugar level > 120 (1= true, 0 = false) restecg= resting electrocardiographic result (0=normal,1 = having ST-T abnormality, 2= probable/definite left ventricular hypertrophy by Estes criteria)
#thalach= max heart rate achieved during exercise
#exang= exercise induced angina
#old peak=ST depression induced by exercise relative to rest
#slope= Slope of peak exercise ST segment (0= unsloping, 1= flat,2= downsloping)
#ca=number of major vessels (0-3) colored by fluoroscopy

In [27]:
#preprocessing data
heart_df.shape

(303, 14)

In [28]:
heart_df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [29]:
heart_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [30]:
heart_df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [31]:
heart_df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [32]:
X=heart_df.drop('target',axis=1)
Y=heart_df['target']
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [33]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [34]:
X_train.shape

(227, 13)

In [35]:
X_test.shape

(76, 13)

Training model using LogisticRegression

In [36]:
model=LogisticRegression()
model.fit(X_train,Y_train)
train_y_pred=model.predict(X_train)
accuracy_score(train_y_pred,Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8590308370044053

In [37]:
test_y_pred=model.predict(X_test)
accuracy_score(test_y_pred,Y_test)
#comparing training and testing data

0.881578947368421

In [38]:
input_data=(43,1,0,115,303,0,1,181,0,1.2,1,0,2)
np_df=np.asarray(input_data)
np_df_reshaped=np_df.reshape(1,-1)
prediction=model.predict(np_df_reshaped)
if prediction[0]==0:
  print('Person does not have a heart disease.')
  print(prediction)
else:
  print('Person has a heart disease.')
  print(prediction)

Person has a heart disease.
[1]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(